/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PlaceholderNFTERC1155 } from "./PlaceholderNFTERC1155";
export type { PlaceholderNFTERC721 } from "./PlaceholderNFTERC721";
export type { PlaceholderNFTERC721A } from "./PlaceholderNFTERC721A";
